export const cartConstants = {
  ADD_ITEM_TO_CART_REQUEST: "ADD_ITEM_TO_CART_REQUEST",
  ADD_ITEM_TO_CART_SUCCESS: "ADD_ITEM_TO_CART_SUCCESS",
  ADD_ITEM_TO_CART_FAILURE: "ADD_ITEM_TO_CART_FAILURE",

  REMOVE_ITEM_FROM_CART_REQUEST: "REMOVE_ITEM_FROM_CART_REQUEST",
  REMOVE_ITEM_FROM_CART_SUCCESS: "REMOVE_ITEM_FROM_CART_SUCCESS",
  REMOVE_ITEM_FROM_CART_FAILURE: "REMOVE_ITEM_FROM_CART_FAILURE",

  GET_CART_ITEMS_REQUEST: "GET_CART_ITEMS_REQUEST",
  GET_CART_ITEMS_SUCCESS: "GET_CART_ITEMS_SUCCESS",
  GET_CART_ITEMS_FAILURE: "GET_CART_ITEMS_FAILURE",

  CLEAR_CART_ITEMS_REQUEST: "CLEAR_CART_ITEMS_REQUEST",
  CLEAR_CART_ITEMS_SUCCESS: "CLEAR_CART_ITEMS_SUCCESS",
  CLEAR_CART_ITEMS_FAILURE: "CLEAR_CART_ITEMS_FAILURE",
};
