export const orderConstants = {
  ORDERS_LIST_REQUEST: "ORDERS_LIST_REQUEST",
  ORDERS_LIST_SUCCESS: "ORDERS_LIST_SUCCESS",
  ORDERS_LIST_FAILURE: "ORDERS_LIST_FAILURE",

  ORDER_LIST_REFETCH_REQUEST: "ORDER_LIST_REFETCH_REQUEST",

  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILURE: "CREATE_ORDER_FAILURE",

  UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
  UPDATE_ORDER_FAILURE: "UPDATE_ORDER_FAILURE",

  DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
  DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
  DELETE_ORDER_FAILURE: "DELETE_ORDER_FAILURE",
};
