export const productConstants = {

    PRODUCT_LIST_REQUEST:'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS:'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAILURE:'PRODUCT_LIST_FAILURE',

    HOME_PAGE_PRODUCT_BANNER_REQUEST:'HOME_PAGE_PRODUCT_BANNER_REQUEST',
    HOME_PAGE_PRODUCT_BANNER_SUCCESS:'HOME_PAGE_PRODUCT_BANNER_SUCCESS',
    HOME_PAGE_PRODUCT_BANNER_FAILURE:'HOME_PAGE_PRODUCT_BANNER_FAILURE',

    PRODUCT_LIST_REFETCH_REQUEST:'PRODUCT_LIST_REFETCH_REQUEST',

    PRODUCT_DETAILS_REQUEST:'PRODUCT_DETAILS_REQUEST',
    PRODUCT_DETAILS_SUCCESS:'PRODUCT_DETAILS_SUCCESS',
    PRODUCT_DETAILS_FAILURE:'PRODUCT_DETAILS_FAILURE',

    PRODUCT_ADD_REQUEST:'PRODUCT_ADD_REQUEST',
    PRODUCT_ADD_SUCCESS:'PRODUCT_ADD_SUCCESS',
    PRODUCT_ADD_FAILURE:'PRODUCT_ADD_FAILURE', 

    PRODUCT_UPDATE_REQUEST:'PRODUCT_UPDATE_REQUEST',
    PRODUCT_UPDATE_SUCCESS:'PRODUCT_UPDATE_SUCCESS',
    PRODUCT_UPDATE_FAILURE:'PRODUCT_UPDATE_FAILURE',

    PRODUCT_DELETE_REQUEST:'PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS:'PRODUCT_DELETE_SUCCESS',
    PRODUCT_DELETE_FAILURE:'PRODUCT_DELETE_FAILURE',
};
