export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    PROFILE_DETAILS_REQUEST: 'USERS_PROFILE_DETAILS_REQUEST',
    PROFILE_DETAILS_SUCCESS: 'USERS_PROFILE_DETAILS_SUCCESS',
    PROFILE_DETAILS_FAILURE: 'USERS_PROFILE_DETAILS_FAILURE',
    
    PROFILE_DETAILS_REFETCH_REQUEST:'USERS_PROFILE_DETAILS_REFETCH_REQUEST',
    
    PROFILE_ADDRESS_UPDATE_REQUEST:'USERS_PROFILE_ADDRESS_UPDATE_REQUEST',
    PROFILE_ADDRESS_UPDATE_SUCCESS:'USERS_PROFILE_ADDRESS_UPDATE_SUCCESS',
    PROFILE_ADDRESS_UPDATE_FAILURE:'USERS_PROFILE_ADDRESS_UPDATE_FAILURE',

    PROFILE_PICTURE_UPDATE_REQUEST:'USERS_PROFILE_PICTURE_UPDATE_REQUEST',
    PROFILE_PICTURE_UPDATE_SUCCESS:'USERS_PROFILE_PICTURE_UPDATE_SUCCESS',
    PROFILE_PICTURE_UPDATE_FAILURE:'USERS_PROFILE_PICTURE_UPDATE_FAILURE',

    PROFILE_PICTURE_DELETE_REQUEST:'USERS_PROFILE_PICTURE_DELETE_REQUEST',
    PROFILE_PICTURE_DELETE_SUCCESS:'USERS_PROFILE_PICTURE_DELETE_SUCCESS',
    PROFILE_PICTURE_DELETE_FAILURE:'USERS_PROFILE_PICTURE_DELETE_FAILURE',
};
